### ISSUE TITLE
反代是不是爆炸了

### ISSUE THREAD

**Issue by huankong233** [mixmoe/HikariSearch#12]
net::ERR_TOO_MANY_REDIRECTS
![image](https://user-images.githubusercontent.com/49610758/212471050-76ae600b-22ba-47a6-9776-f95b9916b16b.png)

**Comment by mnixry** [comment]
你试试直接用源站？我不太想维护反代了……

**Comment by mnixry** [comment]
修好了，应该

**Comment by huankong233** [comment]
主要是用源站，我会被cloudflare拦截，麻了，现在可以了
