### ISSUE TITLE
ascii2d搜索没有结果

### ISSUE THREAD

**Issue by KarisAya** [mixmoe/HikariSearch#6]
色彩特征搜图方式都没有结果，如图
![GP6D )J556CKO }{T K0K 1](https://user-images.githubusercontent.com/51886078/190687637-6a9fd69e-b93e-44cd-9434-8fd0ad1e62f7.png)
执行 `yarn run dev:worker` 的时候有好几页 WARNING
大概不是网的问题
![4)P)LFJBRQOMNC8J58HO 9P](https://user-images.githubusercontent.com/51886078/190687649-33ce1141-b825-4244-b7c1-ac4572264efc.png)
在网站可以搜（同一张图）
![9MD`O ZO)LBWSITIIV5CCEX](https://user-images.githubusercontent.com/51886078/190689229-d1c95775-2593-4e91-bcaf-9fb29cb0043d.png)

**Comment by mnixry** [comment]
可能是选择器匹配不上了，我明天看看

**Comment by mnixry** [comment]
好了，是反代寄了 你再试试
